### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qijianchuan** [professordeng/simple#11]
首页美化下，可以加入图标导航等，主题功能可以简洁，再借鉴一下其他的设计

**Comment by professordeng** [comment]
> 首页美化下，可以加入图标导航等，主题功能可以简洁，再借鉴一下其他的设计

谢谢您的建议，希望建议可以建议可以具体点，本主题不打算添加额外的图标，另外本人时间精力有限，欢迎一起建设该主题。
